project:
  type: website
  output-dir: docs
website:
  title: "Mark's Random Notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    code-fold: true
    # code-tools: true
    code-overflow: wrap
    highlight-style: github
    code-link: true